// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEcZ4eOcP8QdwgMjey4gdAQGo2DP-Lc4M',
    appId: '1:328514935236:web:06fdc237ccb95f1e50ec91',
    messagingSenderId: '328514935236',
    projectId: 'sem-project-auth',
    authDomain: 'sem-project-auth.firebaseapp.com',
    storageBucket: 'sem-project-auth.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD50ZvYiQ6Inj7Xpy025GDPuCrrr-uccSI',
    appId: '1:328514935236:android:540d1c59549eda4750ec91',
    messagingSenderId: '328514935236',
    projectId: 'sem-project-auth',
    storageBucket: 'sem-project-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3pJSn8-eZMgCHCUrszqrO5Oz5XoheA-A',
    appId: '1:328514935236:ios:ea59f7d035b099b250ec91',
    messagingSenderId: '328514935236',
    projectId: 'sem-project-auth',
    storageBucket: 'sem-project-auth.appspot.com',
    iosBundleId: 'com.example.flutterAuthentication',
  );
}
